theme: jekyll-theme-slate
title: The homepage of Jana Sychrova, university student
description: What you will find here are links to projects, publications, and repositories related to the former.
plugins:
  - jemoji
url: "https://jana-sychrova.github.io"
markdown: kramdown
